YEAR = [2018, 2019, 2020, 2021, 2022, 2023]
LOCATION = [
    "Sakhir",
    "Jeddah",
    "Melbourne",
    "Imola",
    "Miami",
    "Barcelona",
    "Monaco",
    "Baku",
    "Montréal",
    "Silverstone",
    "Spielberg",
    "Le Castellet",
    "Budapest",
    "Spa-Francorchamps",
    "Zandvoort",
    "Monza",
    "Marina Bay",
    "Suzuka",
    "Austin",
    "Mexico City",
    "São Paulo",
    "Yas Island",
]
SESSION = ["FP1", "FP2", "FP3", "Q", "S", "SQ", "R"]
